version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: python main.py

  celery-worker:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info

  celery-beat:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - celery-worker
    command: celery -A tasks beat --loglevel=info
