version: '3.8'

services:
  bot:
    build: .
    command: python3 main.py
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq      

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis

  celery_beat:
    build: .
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - celery_worker

volumes:
  rabbitmq_data:
